Table view for itwinGrid
iTwin/admin-components-react pull request #92
Opened 2023-09-05 07:40 UTC by DanishMehmood-bit

![image](https://github.com/iTwin/admin-components-react/assets/64415995/87317435-ff9d-4cf1-9a68-dd8581eeec7b)

2023-09-06 15:09 UTC, raplemie requested changes
It also appears to be missing a `rush change`, which I guess our pipeline should have caught, but somehow didnt.

2023-09-06 15:09 UTC, raplemie commented on packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinGrid.tsx
> +      tableColumnDescription: "ITwin Name",
As per our documentation site, it appears that the i of iTwin is never capitalized: 
<img width="326" alt="image" src="https://github.com/iTwin/admin-components-react/assets/1904889/bd690679-bd2f-4b13-ab4a-55c26f88bac5">

```suggestion
      tableColumnName: "iTwin Number",
      tableColumnDescription: "iTwin Name",
```

2023-09-07 10:06 UTC, DanishMehmood-bit commented on packages/modules/imodel-browser/src/types.ts
> +export type ViewType = "tile" | "cells";
Done

2023-09-07 20:00 UTC, raplemie approved these changes
Thanks for the contribution!

2023-09-07 20:11 UTC, merged